### PR TITLE
The docker-compose builds, so that has to count for something?

### PR DESCRIPTION
**Pull request by Hermanoid**
She'll need to be tested on Jetson hardware

### CODE REVIEW

**Review by yameatmeyourdead — CHANGES_REQUESTED** [review]
Make the CI work!

**Comment by Hermanoid** [comment]
@yameatmeyourdead built built built built

**Comment by Hermanoid** [comment]
https://github.com/CSMRobotics/MATE/issues/35

**Comment by Hermanoid** [comment]
@yameatmeyourdead My son you must review

**Review by yameatmeyourdead — APPROVED** [review]

**Pull request merged**
